// Paren autogenerated this file on 2024-12-23T15:36:38.534851-07:00.

#include <stdio.h>

int main () {
  int i = 20;
  if (i == 10) {
    printf("i is 10\n")
}else if ((i == 15) || (i == 20)) {
    printf("i is 15 or 20\n")
}else if ((i > 0) && (i < 30)) {
    printf("i is between 0 and 30\n")
}else {
    printf("i is not present\n")
};
  return 0;
}

