// Paren autogenerated this file on 2024-12-24T14:00:57.324246-07:00.

{
  if ((x) < (0)) {
    goto negative;
  };
  if ((y) < (0)) {
    {
      negative:
      printf("Negative\n");
      return;
    };
  };
}
