// Paren autogenerated this file on 2024-12-24T09:46:53.860708-07:00.

{
  if (x < 0) {
    goto negative;
  };
  if (y < 0) {
    {
      negative:
      printf("Negative\n");
      return;
    };
  };
}
