// Paren autogenerated this file on 2024-12-23T12:10:47.591315-07:00.

#include <stdio.h>
#include <stdlib.h>

int (square) (int (x)) {
  return ((x) * (x));
}
int (*(map)) (int->int (f), int* (arr), size-t (size)) {
  int (*(result)) = (int (*(~a)))(malloc(((size) * (sizeof(int)))));
  for (size-t (i) = 0; (i < size); (i++)) {
  result[i] = f(arr[i])
};
  return result;
}
int (main) () {
  int[] (numbers) = {1, 2, 3, 4, 5};
  size-t (size) = ((sizeof(numbers)) / (sizeof(numbers[0])));
  int* (result) = map(square, numbers, size);
  for (size-t (i) = 0; (i < size); (i++)) {
  printf("%d", result[((i) + (1))])
  printf("%d", result[i])
};
  printf("\n");
  return 0;
}

