// Paren autogenerated this file on 2024-12-23T14:26:58.098617-07:00.

int (foo_INT) (int (x), int (y)) {
  return ((2) * (((x) + (y))));
}

float (foo_FLOAT) (float (x), float (y)) {
  return ((2) * (((x) + (y))));
}

double (foo_DOUBLE) (double (x), double (y)) {
  return ((2) * (((x) + (y))));
}

