// Paren autogenerated this file on 2024-12-23T09:41:48.528055-07:00.

#include <stdio.h>
int (main) () {
  int (day);
  printf("Enter a number (1-7) to represent a day of the week: ");
  scanf("%d", &day);
  switch (day) {
  case 1:
    printf(Monday\n);
  case 2:
    printf(Tuesday\n);
  case 3:
    printf(Wednesday\n);
  case 4:
    printf(Thursday\n);
  case 5:
    printf(Friday\n);
  case 6:
    printf(Saturday\n);
  case 7:
    printf(Sunday\n);
  default:
    printf(Invalid day number. Please enter a number between 1 and 7.\n);
};
  return 0;
}
