name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Roswell
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        set -ex
        ros config set dynamic-space-size 2048
        curl -L https://qlot.tech/installer | bash
        export PATH="/home/runner/.qlot/bin:$PATH"
        qlot install
        ros run --eval '
          (format t "LISP: ~a (v.~a)~%" (lisp-implementation-type) (lisp-implementation-version))
          (format t "ASDF-VERSION: ~a~%" (asdf:asdf-version))
          (format t "ASDF-CENTRAL-REGISTRY: ~a~%" asdf:*central-registry*)
          (handler-case (asdf:load-system :lispc)
            (error (e) (declare (ignore e)) (uiop:quit 1)))
          (format t "Done. Bye.~%")
          (uiop:quit 0)
        '
