name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing Github Action
      run: echo Hello, world!
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }} # TODO ?
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        set -ex
        pwd
        ls -al
        ros config set dynamic-space-size 2048
        ros run --eval '
          (pprint "hello bye~%")
          (pprint (asdf:asdf-version))
          (pprint (asdf:component-version (asdf:find-system :local-time)))  (exit)
        '
