name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Testing Github Action
      run: echo Hello, world!
    - name: Install Roswell
      env:
        LISP: ${{ matrix.lisp }} # TODO ?
      run: |
        curl -L https://raw.githubusercontent.com/roswell/roswell/v22.12.14.113/scripts/install-for-ci.sh | sh
    - name: Run test
      run: |
        set -ex
        ros config set dynamic-space-size 2048
        ros run --eval '
          (format t "LISP: ~a (v.~a)~%" (lisp-implementation-type) (lisp-implementation-version))
          (format t "ASDF-VERSION: ~a~%" (asdf:asdf-version))
          (format t "ASDF-CENTRAL-REGISTRY: ~a~%" asdf:*central-registry*)
          (asdf:load-system :lispc)
          (format t "Done. Bye.~%")
          (exit)
        '
